### ISSUE TITLE
The centroids of some countries seem not right.

### ISSUE THREAD

**Issue by qzhang6862** [gavinr/world-countries-centroids#8] opened 2023-01-31 22:33 UTC
The centroid of New Zealand seems the centroid of the South Island only.
The centroid of Malaysia seems the centroid of Sarawak and Sabah.
The centroid of Indonesia seems the centroid of Indonesian Kalimantan.
The centroid of the Philippines seems the centroid of Luzon Island.
The centroid of Italy and Greece seems the centroid of the mainland only without islands.
...

**Comment by merwok** [comment] 2023-01-31 22:53
This was done on purpose: https://github.com/gavinr/world-countries-centroids/issues/7#issuecomment-1229599050

**Comment by qzhang6862** [comment] 2023-02-01 05:39
I see. But a centroid is not necessary to be in a polygon. I would like a version of this application with parameters like withinPolygon=true/false.

**Comment by gavinr** [comment] 2023-02-01 05:41
Thank you for the feedback.

This is a duplicate of: https://github.com/gavinr/world-countries-centroids/issues/7#issuecomment-1411180779

**Closed as completed by gavinr** 2023-02-01 05:41 UTC
